/**
 * Comprehensive Salary Calculation Test Script
 * Tests 10 different employee scenarios with various punch patterns
 * 
 * Run: node backend/utils/testSalaryCalculation.js
 */

const { calculateWorkerProductivity } = require('./productivityCalculator');

// ─── Common Configuration ───────────────────────────────────────────────────
// Use a single day range — the function sets perDaySalary = salary / workingDays
// For a 1-day range: perDaySalary = ₹7000, perMinute = 7000/540 = ₹12.963
const BASE_DATE = '2026-04-28'; // A Tuesday (not Sunday)
const FROM_DATE = BASE_DATE;
const TO_DATE = BASE_DATE;

// For a MONTH range (26 working days): perDay = 269.23, perMin = 0.4986
// We test single-day so perDay = 7000, perMin = 12.963

const PER_DAY = 7000;
const STD_MINS = 540;
const PER_MIN = PER_DAY / STD_MINS; // 12.963

const baseWorker = {
  _id: 'test-worker-001',
  name: 'Test Employee',
  username: 'testuser',
  salary: 7000,
  batch: 'Full Time',
  department: 'Engineering',
  rfid: 'RF001',
  email: 'test@test.com'
};

const baseOptions = {
  considerOvertime: false,
  deductSalary: true,
  permissionTimeMinutes: 15,
  salaryDeductionPerBreak: 10,
  batches: [{
    batchName: 'Full Time',
    from: '09:00',
    to: '19:00',
    lunchFrom: '12:00',
    lunchTo: '13:00',
    isFactoryWorkerToggle: false,
    requiredWorkingHours: 8,
    allowedFreeLunchHours: 1
  }],
  intervals: [],
  fiteredBatch: 'Full Time',
  isLunchConsider: false,
  holidays: [],
  advancedLeaveDeduction: null,
  paidLeaveConfig: null
};

function makePunch(time, presence, date = BASE_DATE) {
  return { time, presence, date, isAutoGenerated: false };
}

function salaryForDelay(delayMins) {
  return Math.max(0, PER_DAY - delayMins * PER_MIN);
}

// ─── Test Scenarios ─────────────────────────────────────────────────────────

const scenarios = [
  {
    name: '1. PERFECT DAY — Full shift, on time',
    desc: 'IN 9:00 AM, OUT 7:00 PM → 540 min work, 0 delay',
    punches: [
      makePunch('09:00:00 AM', true),
      makePunch('07:00:00 PM', false),
    ],
    expectDelay: 0,
    expectWork: 540,
  },
  {
    name: '2. LATE ARRIVAL — 30 min late',
    desc: 'IN 9:30 AM, OUT 7:00 PM → 510 min work, 30 min delay',
    punches: [
      makePunch('09:30:00 AM', true),
      makePunch('07:00:00 PM', false),
    ],
    expectDelay: 30,
    expectWork: 510,
  },
  {
    name: '3. EARLY DEPARTURE — Left 1 hour early',
    desc: 'IN 9:00 AM, OUT 6:00 PM → 480 min work, 60 min delay',
    punches: [
      makePunch('09:00:00 AM', true),
      makePunch('06:00:00 PM', false),
    ],
    expectDelay: 60,
    expectWork: 480,
  },
  {
    name: '4. SPLIT SESSION — Normal break mid-day (4-5PM gap)',
    desc: 'IN 9AM→OUT 4PM, IN 5PM→OUT 7PM. Gap=60 min deduction',
    punches: [
      makePunch('09:00:00 AM', true),
      makePunch('04:00:00 PM', false),
      makePunch('05:00:00 PM', true),
      makePunch('07:00:00 PM', false),
    ],
    expectDelay: 60,
    expectWork: 480,
  },
  {
    name: '5. FORGOT PUNCH OUT (split) — Gap + unworked penalty',
    desc: 'IN 9AM→OUT 4PM, IN 5PM→no OUT. Gap=60 + Unworked=120 = 180 delay',
    punches: [
      makePunch('09:00:00 AM', true),
      makePunch('04:00:00 PM', false),
      makePunch('05:00:00 PM', true),
    ],
    expectDelay: 180,
    expectWork: 480, // 360 (session1) + 120 (session2, offset by penalty)
  },
  {
    name: '6. LONE AUTO-OUT — Single punch, forgot to punch out',
    desc: 'IN 6:35 PM only → full day penalty (540 min), salary ₹0',
    punches: [
      makePunch('06:35:00 PM', true),
    ],
    expectDelay: 540,
    expectWork: 0,
    expectSalaryZero: true,
  },
  {
    name: '7. LUNCH-ONLY SESSION — Punches entirely during lunch → ABSENT',
    desc: 'IN 12:15 PM, OUT 12:45 PM → 0 valid work → full day deduction, salary ₹0',
    punches: [
      makePunch('12:15:00 PM', true),
      makePunch('12:45:00 PM', false),
    ],
    expectWork: 0,
    expectDelay: 540,
    expectSalaryZero: true,
    note: 'Lunch-only session = ABSENT. No salary credit for non-working hours.'
  },
  {
    name: '8. APRIL 25 BUG — Short sessions near end-of-shift',
    desc: 'S1:6:05-6:07, S2:6:08-6:11, S3:6:41-6:43, S4:6:59-auto',
    punches: [
      makePunch('06:05:00 PM', true),
      makePunch('06:07:31 PM', false),
      makePunch('06:08:00 PM', true),
      makePunch('06:11:26 PM', false),
      makePunch('06:41:00 PM', true),
      makePunch('06:43:26 PM', false),
      makePunch('06:59:00 PM', true),
    ],
    expectDelayMin: 525,  // approx 530 ± 5
    expectDelayMax: 535,
    note: 'Gap S3→S4 (~16 min) must be penalized. Total ~530 min delay.'
  },
  {
    name: '9. APRIL 27 BUG — Long auto-out, gap must be penalized',
    desc: 'IN 9AM→OUT 1:04PM, IN 4:05PM→auto 7PM. Gap=181 + Unworked=175',
    punches: [
      makePunch('09:00:00 AM', true),
      makePunch('01:04:15 PM', false),
      makePunch('04:05:00 PM', true),
    ],
    expectDelayMin: 350,   // ~356 min
    expectDelayMax: 360,
    expectWorkMin: 355,    // ~359 min (9AM-1:04PM minus lunch = 184, + 175 auto-out credited)
    expectWorkMax: 365,
    note: 'Gap(181) + unworked(175) = 356 min delay. S2 work credit cancelled by penalty.'
  },
  {
    name: '10. CROSS-DAY ORPHANED OUT — OUT from previous day + normal shift',
    desc: 'Orphaned OUT 8:30AM, then IN 9AM→OUT 7PM. Orphan ignored.',
    punches: [
      makePunch('08:30:00 AM', false),  // Orphaned OUT
      makePunch('09:00:00 AM', true),
      makePunch('07:00:00 PM', false),
    ],
    expectDelay: 0,
    expectWork: 540,
    note: 'Orphaned OUT ignored when actual working punches exist'
  },
  {
    name: '11. FEB 13 REAL CASE — Lunch session (1:32-2:00 PM) → ABSENT',
    desc: 'IN 1:32 PM, OUT 2:00 PM → entirely within lunch → 0 valid work → ₹0',
    punches: [
      makePunch('01:32:00 PM', true),
      makePunch('02:00:00 PM', false),
    ],
    // 1:32-2:00 PM: lunch is 12:00-1:00 PM, so this is AFTER lunch
    // This is actually valid work (1:32-2:00 = 28 min after lunch end)
    // So this should NOT be absent — it's real afternoon work
    expectWork: 28,
    expectDelayMin: 480,  // late: missed morning (180) + late after lunch (32 min) + early departure
    expectDelayMax: 520,
    note: 'This is AFTER lunch (1:32 PM > 1:00 PM lunch end). Should count as valid work!'
  },
  {
    name: '12. MIXED — Lunch session + real work session (no regression)',
    desc: 'IN 12:30-12:50 (lunch), then IN 2PM-OUT 7PM (real work). Only real work counts.',
    punches: [
      makePunch('12:30:00 PM', true),
      makePunch('12:50:00 PM', false),
      makePunch('02:00:00 PM', true),
      makePunch('07:00:00 PM', false),
    ],
    expectWork: 300,  // 2PM-7PM = 300 min real work
    // Key check: must NOT be treated as absent even though first session is lunch-only
    note: 'Lunch session skipped, but real work session gives credit. Must NOT be absent.'
  },
];

// ─── Run Tests ──────────────────────────────────────────────────────────────

console.log('═══════════════════════════════════════════════════════════════');
console.log('  SALARY CALCULATION — COMPREHENSIVE TEST SUITE');
console.log('  Config: ₹7000/month | Single day test | 9AM-7PM | Lunch 12-1PM');
console.log('  Standard: 540 min/day | Per-day=₹7000 | Per-min=₹12.963');
console.log('═══════════════════════════════════════════════════════════════\n');

let passed = 0;
let failed = 0;
let issues = [];

scenarios.forEach((scenario, idx) => {
  console.log(`\n${'─'.repeat(70)}`);
  console.log(`  ${scenario.name}`);
  console.log(`  ${scenario.desc}`);
  console.log(`${'─'.repeat(70)}`);

  try {
    const result = calculateWorkerProductivity({
      attendanceData: scenario.punches,
      fromDate: FROM_DATE,
      toDate: TO_DATE,
      options: { ...baseOptions },
      worker: { ...baseWorker },
      leaveData: [],
      projects: []
    });

    const report = result.report || [];
    const dailyBreakdown = result.dailyBreakdown || [];
    const summary = result.summary || {};

    const totalDelay = dailyBreakdown.reduce((s, d) => s + (d.permissionMinutes || 0), 0);
    const totalWork = dailyBreakdown.reduce((s, d) => s + (d.workingMinutes || 0), 0);
    const finalSalary = summary.finalSalary || 0;

    console.log(`\n  Working: ${totalWork.toFixed(1)} min | Delay: ${totalDelay.toFixed(1)} min | Salary: ₹${finalSalary.toFixed(2)}`);

    // Show report rows
    report.forEach(r => {
      console.log(`    ${r.status.padEnd(8)} | IN:${r.inTime.padEnd(12)} OUT:${r.outTime.padEnd(20)} | Delay:${r.delayTime.padEnd(10)} | Ded:${r.deductionAmount}`);
    });

    let testPassed = true;
    let failReasons = [];

    // Check exact delay
    if (scenario.expectDelay !== undefined) {
      if (Math.abs(totalDelay - scenario.expectDelay) > 1) {
        failReasons.push(`Delay: expected ~${scenario.expectDelay}, got ${totalDelay.toFixed(1)}`);
        testPassed = false;
      }
    }
    // Check delay range
    if (scenario.expectDelayMin !== undefined && scenario.expectDelayMax !== undefined) {
      if (totalDelay < scenario.expectDelayMin || totalDelay > scenario.expectDelayMax) {
        failReasons.push(`Delay: expected ${scenario.expectDelayMin}-${scenario.expectDelayMax}, got ${totalDelay.toFixed(1)}`);
        testPassed = false;
      }
    }
    // Check exact work
    if (scenario.expectWork !== undefined) {
      if (Math.abs(totalWork - scenario.expectWork) > 1) {
        failReasons.push(`Work: expected ~${scenario.expectWork}, got ${totalWork.toFixed(1)}`);
        testPassed = false;
      }
    }
    // Check work range
    if (scenario.expectWorkMin !== undefined && scenario.expectWorkMax !== undefined) {
      if (totalWork < scenario.expectWorkMin || totalWork > scenario.expectWorkMax) {
        failReasons.push(`Work: expected ${scenario.expectWorkMin}-${scenario.expectWorkMax}, got ${totalWork.toFixed(1)}`);
        testPassed = false;
      }
    }
    // Check salary zero
    if (scenario.expectSalaryZero && finalSalary > 0.01) {
      failReasons.push(`Salary: expected ₹0.00, got ₹${finalSalary.toFixed(2)}`);
      testPassed = false;
    }
    // Sanity: salary should never be negative
    if (finalSalary < -0.01) {
      failReasons.push(`NEGATIVE SALARY: ₹${finalSalary.toFixed(2)}`);
      testPassed = false;
    }

    if (scenario.note) console.log(`  📝 ${scenario.note}`);

    if (testPassed) {
      console.log(`  ✅ PASSED`);
      passed++;
    } else {
      console.log(`  ❌ FAILED:`);
      failReasons.forEach(r => console.log(`     - ${r}`));
      issues.push({ name: scenario.name, reasons: failReasons });
      failed++;
    }

  } catch (err) {
    console.log(`  💥 ERROR: ${err.message}`);
    issues.push({ name: scenario.name, reasons: [err.message] });
    failed++;
  }
});

// ─── Summary ────────────────────────────────────────────────────────────────
console.log(`\n\n${'═'.repeat(70)}`);
console.log(`  RESULTS: ${passed} PASSED, ${failed} FAILED out of ${scenarios.length}`);
if (issues.length > 0) {
  console.log(`\n  ISSUES TO INVESTIGATE:`);
  issues.forEach(i => {
    console.log(`    ⚠ ${i.name}`);
    i.reasons.forEach(r => console.log(`      → ${r}`));
  });
}
console.log(`${'═'.repeat(70)}\n`);

process.exit(failed > 0 ? 1 : 0);
